version: '3.8'

services:
  frontend:
    image: youclip-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - youclip-network
    restart: unless-stopped

  backend:
    image: youclip-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend/downloads:/app/downloads
    networks:
      - youclip-network
    restart: unless-stopped
    environment:
      - PORT=5000
      - NODE_ENV=production

networks:
  youclip-network:
    driver: bridge