version: '2.26'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - youclip-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/downloads:/app/downloads
    networks:
      - youclip-network
    restart: unless-stopped
    environment:
      - PORT=5000
      - NODE_ENV=production

networks:
  youclip-network:
    driver: bridge